services:
  wordpress:
    image: wordpress
    networks:
      - frontend
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend

networks:
  frontend:
  backend:
    internal: true
